root = "."
tmp_dir = "tmp"

[build]
  cmd = "CGO_ENABLED=1 go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "bin", "models", "migrations", "coverage"]
  include_ext = ["go"]
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500

[log]
  main_only = false
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
